name: Cleanup Past Events

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:      # <-- add this line for manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Remove past events
        run: |
          node cleanup-events.js

      - name: Commit & push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add wardboard/events.json

          # Only commit if there are changes
          if git diff --cached --quiet; then
            echo "No past events to remove."
            exit 0
          fi

          git commit -m "Cleanup: Remove past events automatically"
          git push origin HEAD:${{ github.ref_name }}
